### ISSUE TITLE
Cookies used to save the game only last one week

### ISSUE THREAD

**Issue by Redd500** [Naruyoko/many-to-do-less-you-have-to#10]
This means the achievement for leaving the game for one week and coming back is impossible to get, and also that save games will disappear far faster than other games.

**Comment by Naruyoko** [comment]
Wow I forgot that I set expire in a week and the achievement will make the save disappear... Willfix

**Comment by Naruyoko** [comment]
As I described in the previous comment, I've extended the length to a year in the recent patch.

**Comment by Redd500** [comment]
Yep, looks like it's fixed!
