### ISSUE TITLE
Screen twitching

### ISSUE THREAD

**Issue by LoganDungeon** [Naruyoko/many-to-do-less-you-have-to#7]
Since the last Update the screen is constantly twitching around. And there seems no way to fix it. Even zooming in or out doesn't do anything

**Comment by Naruyoko** [comment]
Is it twitching up and down or shaking?

**Comment by Naruyoko** [comment]
Also, how much have you progressed?

**Comment by LoganDungeon** [comment]
like this: https://imgur.com/a/XLRbwkN

**Comment by Naruyoko** [comment]
That is an effect. Added disable shaking option! It is under the buttons in Unit Conversion tab.
