### ISSUE TITLE
Fast-changing numbers with decimal values cause flapping of text.

### ISSUE THREAD

**Issue by ConstipatedNinja** [Naruyoko/many-to-do-less-you-have-to#8]
Hello!

Overall this is a pretty low-priority thing.

Because the existivity number updates every 0.1s, if you have an existivity per second that has a 5 in the hundredths digit, the existivity and chance line will rapidly change length because the existivity value will swap back and forth between having one digit to the right of the decimal and having two. I'm sure that adding `.toFixed(2)` is all you really need to fix that.

**Comment by Naruyoko** [comment]
I may not be able to do .toFixed(), but I can add option to disable wrapping;

**Comment by Naruyoko** [comment]
And what I mean I can I will.

**Comment by ConstipatedNinja** [comment]
No worries! You've made a fun game to play and I appreciate every moment you use to make it even better! And yeah, sorry, I forgot that .toFixed was part of FF4 and not standard. I most often code in perl, python, and bash, and only dabble in js.

PS, you're the best!

**Comment by Naruyoko** [comment]
Added disable wrapping option in footer(hover over the arrown on left-bottom corner).
